#生成配置
markdown: redcarpet
highlighter: pygments
permalink: /:title.html
paginate: 15
baseurl: "/"
exclude: ['vendor', 'README.md', 'Gemfile', 'Gemfile.lock', 'config.ru', 'unicorn.rb', 'Procfile']

#站点基础配置
title: '剑行者'
subTitle: 像剑一样不为世事打磨圆滑...
description: 那一天我老了，就不折腾了
keywords: 剑行者,java,ios,swift
url: http://www.psvmc.cn

#菜单配置
nav:
  - text: 首页
    url: /index.html
    target: _self
  - text: 日期归档
    url: /archives.html
    target: _self
  - text: 分类归档
    url: /category.html
    target: _self
  - text: 我的工具
    url: /zjtools/index.html
    target: _self
  - text: 我的插件
    url: /zjplugin/index.html
    target: _self
  - text: 第三方插件
    url: /otplugin/index.html
    target: _self
  - text: 示例演示
    url: /zjdemo/index.html
    target: _self


#theme config
themes: /jekyll-themes/ztheme

#配置你喜欢的顶部背景图片
headimg:
  - item: /jekyll-themes/ztheme/images/hdbg01.jpg
  - item: /jekyll-themes/ztheme/images/hdbg02.jpg
  - item: /jekyll-themes/ztheme/images/hdbg03.jpg

#关注我
follow:
  - class: fa-github
    url: https://github.com/psvmc
  - class: fa-rss
    url: /atom.xml

#作者信息
author:
  link: http://psvmc.github.io
  name: psvmc

#评论信息
disqus:
  config: false
  id: psvmc

duoshuo:
  config: true
  id: psvmc
