#生成配置
markdown: redcarpet
highlighter: pygments
permalink: /:title.html
paginate: 15
baseurl: "/"
exclude: ['vendor', 'README.md', 'Gemfile', 'Gemfile.lock', 'config.ru', 'unicorn.rb', 'Procfile']

#站点基础配置
title: PSVMC
subTitle: 苦逼程序猿
description: 没事瞎倒腾。
keywords: psvmc,java,jekyll,swift
url: http://www.psvmc.cn

#菜单配置
nav:
  - text: 首页
    url: /index.html
  - text: 日期归档
    url: /archives.html
  - text: 分类归档
    url: /category.html

#theme config
themes: /themes/ztheme

#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/ztheme/images/hdbg01.jpg
  - item: /themes/ztheme/images/hdbg02.jpg
  - item: /themes/ztheme/images/hdbg03.jpg
  - item: /themes/ztheme/images/hdbg04.jpg

#关注我
follow:
  - class: fa-github
    url: https://github.com/psvmc
  - class: fa-rss
    url: /atom.xml

#作者信息
author:
  link: http://psvmc.github.io
  name: psvmc

#评论信息
disqus:
  config: false
  id: psvmc

duoshuo:
  config: true
  id: psvmc